---
- name: This sets up an httpd webserver
  hosts: all
  become: yes
  tasks:
  - name: Install apache packages
    yum:
      name: httpd
      state: present
  - name: ensure httpd is running
    ansible.builtin.service:
      name: httpd
      state: started
  - name: Enable firewalld
    service: name=firewalld state=started enabled=yes
  - name: Allow http/https
    command: firewall-cmd --permanent --add-port=80/tcp
  - name: Bounce firewalld
    command: firewall-cmd --reload
