---
- name: tomcat install
  hosts: all
  become: yes
  tasks:
  - name: Install OpenJDK
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: download tomcat server packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.62/bin/apache-tomcat-9.0.62.tar.gz
      dest: /opt

  - name: extract tomcat packages
    unarchive:
      src: /opt/apache-tomcat-9.0.62.tar.gz
      dest: /opt
      remote_src: yes

  - name: start tomcat services
    shell: nohup /opt/apache-tomcat-9.0.62/bin/startup.sh

  - name: Enable firewalld
    service: name=firewalld state=started enabled=yes
    
  - name: Allow port 8080
    command: firewall-cmd --permanent --add-port=8080/tcp
    
  - name: Bounce firewalld
    command: firewall-cmd --reload
